services:
  postgres:
    image: postgres:16
    container_name: staybook-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"
    volumes:
      - staybook_postgres_data:/var/lib/postgresql/data

volumes:
  staybook_postgres_data: